ALTER TABLE "SystemSetting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InviteCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserBalance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PointTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GenerationTask" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Template" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Asset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProviderCallLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AdminLog" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "User_inviteCodeId_idx" ON "User"("inviteCodeId");
CREATE INDEX IF NOT EXISTS "GenerationTask_templateId_idx" ON "GenerationTask"("templateId");
CREATE INDEX IF NOT EXISTS "Asset_templateId_idx" ON "Asset"("templateId");
